### ISSUE TITLE
Command does not match expected

### ISSUE THREAD

**Issue by jfcaron3** [haata/ugsimple-usb-gpib#5]
Hi, this is my first time trying to use UGSimple.  I'm on a late-2011 Macbook Pro running OSX 10.11.6.
My python version is 3.6 from MacPorts, pyusb 1.0.0 from MacPorts, and libusb 1.0.21 from MacPorts.  I've just "git cloned" this repo and I am trying to run the example code.  My device is a Tektronix PS2521G power supply.

When I try to run the example.py, I get the following output:

```1.0
LQ ELECTRONICS CORP
011e7f7f
array('B')
ERROR: '0x 3' does not match expected command '0x33
Traceback (most recent call last):
  File "example.py", line 50, in <module>
    print ( mygpib.read( 0x9 ) )
  File "/Users/jfcaron/Software/ugsimple/ugsimple-usb-gpib/ugsimple/GPIB.py", line 291, in read
    byteData = byteData[:-1]
TypeError: 'NoneType' object is not subscriptable
```

The output is the same regardless of whether the PS2521G is connected or powered on.  Note that I did fix a small bug on line 168 of GPIB.py:
`print ("ERROR: '0x{0:2x}' does not match expected command '0x{1:2x}".format( command, address ) )`
Previously it was printing the "command" argument twice, but I changed the format string so it prints the "command" and "address" arguments (0x 3 and 0x33 in the output above).

**Comment by cellularmitosis** [comment]
I'm running into the same error when interfacing to an HP 34401A which is in "talk only" mode (it just continually transmits values without needing to send it a command).

In my python script, I'm just trying to read in an infinite loop:

```
#!/usr/bin/env python3

from ugsimple.GPIB import UGSimpleGPIB

if __name__ == '__main__':
    mygpib = UGSimpleGPIB(debug_mode=True)
    addr = mygpib.query_devices()[0]
    while True:
        print(float(mygpib.read(addr)))
```

This works the first time through the loop, but on the second iteration it throws the "does not match expected command" error:

```
5.4594761
ERROR: '0x13' does not match expected command '0x13
```

**Comment by cellularmitosis** [comment]
Similar situation when I try to issue the "*IDN?" command in a loop.  It works once and then fails.

```#!/usr/bin/env python3

from ugsimple.GPIB import UGSimpleGPIB

if __name__ == '__main__':
    mygpib = UGSimpleGPIB()
    addr = mygpib.query_devices()[0]
    while True:
        mygpib.write(addr, "*IDN?")
        print(mygpib.read(addr))
```

```
b'HEWLETT-PACKARD,34401A,0,10-5-2'
ERROR: '0x22' does not match expected command '0x22
Traceback (most recent call last):
  File "./idn.py", line 10, in <module>
    print(mygpib.read(addr))
  File "/home/cell/github/haata/ugsimple-usb-gpib/ugsimple/GPIB.py", line 291, in read
    byteData = byteData[:-1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cellularmitosis** [comment]
Here's the full output of the "talk only" mode loop:

```
DEVICE ID 04d8:000c on Bus 002 Address 002 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x200 USB 2.0
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :    0x8 (8 bytes)
 idVendor               : 0x04d8
 idProduct              : 0x000c
 bcdDevice              :    0x0 Device 0.0
 iManufacturer          :    0x1 Microchip Technology Inc.
 iProduct               :    0x2 Microchip Custom USB Device
 iSerialNumber          :    0x0 
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 100 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :   0x32 (100 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0 
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
  CONFIGURATION 1: 100 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :   0x32 (100 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0 
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0 
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
WRITE: [52, 2]
array('B', [52, 4, 11, 69, 10]) 5
READ CMD: 52
array('B', [4, 11, 69, 10]) 4
READ LEN: 4
array('B', [11, 69, 10]) 3
READ DATA: array('B', [11, 69])
DEVICES: array('B', [11])
READ REQ: bytearray(b'\x0b')
WRITE: [51, 3, 11]
array('B', [10]) 1
array('B', [51, 19, 43, 53, 46, 52, 54, 51, 53, 49, 50, 53, 48, 69, 43, 48, 48, 13, 10]) 19
READ CMD: 51
array('B', [19, 43, 53, 46, 52, 54, 51, 53, 49, 50, 53, 48, 69, 43, 48, 48, 13, 10]) 18
READ LEN: 19
array('B', [43, 53, 46, 52, 54, 51, 53, 49, 50, 53, 48, 69, 43, 48, 48, 13, 10]) 17
READ DATA: array('B', [43, 53, 46, 52, 54, 51, 53, 49, 50, 53, 48, 69, 43, 48, 48, 13, 10])
READ REPLY: b'+5.46351250E+00\r'
5.4635125
READ REQ: bytearray(b'\x0b')
WRITE: [51, 3, 11]
array('B', [51, 19, 43, 53, 46, 52, 54, 51, 53, 49, 53, 48, 48, 69, 43, 48, 48, 13, 10]) 19
array('B', [19, 43, 53, 46, 52, 54, 51, 53, 49, 53, 48, 48, 69, 43, 48, 48, 13, 10]) 18
ERROR: '0x13' does not match expected command '0x13
Traceback (most recent call last):
  File "./talk-only.py", line 10, in <module>
    print(float(mygpib.read(addr)))
  File "/home/cell/github/haata/ugsimple-usb-gpib/ugsimple/GPIB.py", line 291, in read
    byteData = byteData[:-1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cellularmitosis** [comment]
Ok, looks like I got this particular use-case working.

I changed `device_read` such that if the command (first byte) isn't what was expected, it assumes there is no command byte, and instead interprets the first byte as the length of the message:

```python
	def device_read( self, address ):
		# Read USB a single byte to see if a valid command has been received
		command = self.usb_read()[0]
		if command != address:
			print ("ERROR: '0x{0:2x}' does not match expected command '0x{1:2x}'".format( command, address ) )
			print(command)
			print(address)
#			return None

		if self.debug_mode:
			print ( "READ CMD:", command )

		# Valid command, read next byte to determine length of command
		if command != address:
			length = command
		else:
			length = self.usb_read()[0]
```

This seems to work!

**Comment by cellularmitosis** [comment]
PR submitted!  https://github.com/haata/ugsimple-usb-gpib/pull/6
